version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matcha
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"